@startuml
autonumber
participant "MainActivity" as MA
participant "SplashScreen" as SS
participant "RootViewModel" as RVM
participant "MonatsblitzApp" as App
participant "AppNavHost" as Nav

MA -> SS : installSplashScreen()
activate SS
MA -> RVM : initialRoute beobachtet
activate RVM
RVM -> RVM : determineInitialRoute()
RVM --> MA : initialRoute != null
deactivate RVM
SS -> MA : finish splash
deactivate SS

MA -> App : <<create>>
activate App
App -> Nav : <<render>>
activate Nav
Nav -> Nav : Navigiere zu startDestination\n(Setup oder Crosstable)
@enduml
