@startuml
autonumber
participant "MainActivity" as MA
participant "RootScreen" as RS
participant "RootViewModel" as RVM
participant "TournamentStorage" as TS
participant "HomeScreen" as Home
participant "TournamentScreen" as Tour

MA -> RS : <<create>>
activate RS
RS -> RVM : beobachtet uiState
activate RVM
RVM -> TS : getTournamentState()
activate TS
TS --> RVM : Status (z.B. null)
deactivate TS
RVM --> RS : state: ReadyWithoutTournament
deactivate RVM
RS -> Home : <<render>>
deactivate RS

User -> Home : "Turnier starten"
activate Home
Home -> "HomeViewModel" as HVM : createTournament()
activate HVM
HVM -> TS : saveTournamentState(id)
activate TS
TS --> RVM : <<trigger Flow update>>
deactivate TS
activate RVM
RVM --> RS : state: ReadyWithTournament(id)
deactivate RVM
RS -> Tour : <<render>>
deactivate Home
deactivate HVM
@enduml
